export default [
  {
    _id: "A101",
    title: "Propulsion Assignment",
    course: "RS101",
    description:
      "The assignment is <span style='color:red'>available online</span><br/><br/>Submit a link to the landing page of your Web application running on <a href='https://www.netlify.com' target='_blank'>Netlify</a>.<br/><br/>The landing page should include the following:<br/>• Your full name and section<br/>• Links to each of the lab assignments<br/>• Link to the Kanbas application<br/>• Links to all relevant source code repositories<br/><br/>The Kanbas application should include a link to navigate back to the landing page.",
    points: 100,
    availableFrom: "2024-05-06T00:00:00",
    dueDate: "2024-05-13T23:59:00",
    untilDate: null,
    group: "ASSIGNMENTS",
    displayGradeAs: "Percentage",
    submissionType: "Online",
    onlineEntryOptions: ["Text Entry", "Website URL", "Media Recordings"],
    assignTo: ["Everyone"],
  },
  {
    _id: "A102",
    title: "Combustion Analysis",
    course: "RS101",
    description:
      "Analyze combustion efficiency for a sample engine using MATLAB.<br/>Upload a PDF report with graphs and your findings.",
    points: 100,
    availableFrom: "2024-05-15T00:00:00",
    dueDate: "2024-05-22T23:59:00",
    untilDate: null,
    group: "ASSIGNMENTS",
    displayGradeAs: "Points",
    submissionType: "Online",
    onlineEntryOptions: ["File Uploads"],
    assignTo: ["Everyone"],
  },
  {
    _id: "A103",
    title: "Nozzle Design Project",
    course: "RS101",
    description:
      "Design a supersonic nozzle and calculate thrust performance for given conditions.",
    points: 200,
    availableFrom: "2024-06-01T00:00:00",
    dueDate: "2024-06-15T23:59:00",
    untilDate: null,
    group: "PROJECTS",
    displayGradeAs: "Points",
    submissionType: "Online",
    onlineEntryOptions: ["File Uploads", "Website URL"],
    assignTo: ["Everyone"],
  },
  {
    _id: "A201",
    title: "Aerodynamics Quiz",
    course: "RS102",
    description:
      "Short quiz covering aerodynamic principles from lectures 3–6.",
    points: 50,
    availableFrom: "2024-05-01T00:00:00",
    dueDate: "2024-05-05T23:59:00",
    untilDate: null,
    group: "QUIZZES",
    displayGradeAs: "Points",
    submissionType: "Online",
    onlineEntryOptions: ["Text Entry"],
    assignTo: ["Everyone"],
  },
  {
    _id: "A202",
    title: "Flow Analysis",
    course: "RS102",
    description:
      "Perform CFD analysis for a laminar pipe flow and document the results.",
    points: 120,
    availableFrom: "2024-05-10T00:00:00",
    dueDate: "2024-05-20T23:59:00",
    untilDate: null,
    group: "ASSIGNMENTS",
    displayGradeAs: "Percentage",
    submissionType: "Online",
    onlineEntryOptions: ["File Uploads"],
    assignTo: ["Section 1", "Section 2"],
  },
  {
    _id: "A203",
    title: "Heating Analysis",
    course: "RS102",
    description:
      "Analyze the heat transfer efficiency for finned tubes using Python scripts provided.",
    points: 150,
    availableFrom: "2024-05-20T00:00:00",
    dueDate: "2024-05-28T23:59:00",
    untilDate: null,
    group: "PROJECTS",
    displayGradeAs: "Points",
    submissionType: "Online",
    onlineEntryOptions: ["File Uploads", "Text Entry"],
    assignTo: ["Everyone"],
  },
  {
    _id: "A301",
    title: "Structural Design Task",
    course: "RS103",
    description: "Design a beam for minimal deflection under uniform loading.",
    points: 100,
    availableFrom: "2024-06-10T00:00:00",
    dueDate: "2024-06-20T23:59:00",
    untilDate: null,
    group: "ASSIGNMENTS",
    displayGradeAs: "Points",
    submissionType: "Online",
    onlineEntryOptions: ["File Uploads"],
    assignTo: ["Everyone"],
  },
  {
    _id: "A302",
    title: "Orbital Calculations",
    course: "RS103",
    description:
      "Calculate orbital parameters for a satellite in low Earth orbit. Submit your MATLAB or Python notebook.",
    points: 200,
    availableFrom: "2024-06-15T00:00:00",
    dueDate: "2024-06-25T23:59:00",
    untilDate: null,
    group: "ASSIGNMENTS",
    displayGradeAs: "Points",
    submissionType: "Online",
    onlineEntryOptions: ["File Uploads"],
    assignTo: ["Everyone"],
  },
  {
    _id: "A303",
    title: "Systems Engineering Exam",
    course: "RS103",
    description:
      "Final written exam covering all modules of the Systems Engineering course.",
    points: 300,
    availableFrom: "2024-06-30T00:00:00",
    dueDate: "2024-07-05T23:59:00",
    untilDate: null,
    group: "EXAMS",
    displayGradeAs: "Percentage",
    submissionType: "On Paper",
    onlineEntryOptions: [],
    assignTo: ["Everyone"],
  },
];
